version: "3.9"

services:
  search-service:
    build:
      context: .
      dockerfile: services/search-service/Dockerfile
    environment:
      - PORT=4001
    expose:
      - "4001"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:4001/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 5s
      timeout: 3s
      retries: 3

  inventory-service:
    build:
      context: .
      dockerfile: services/inventory-service/Dockerfile
    environment:
      - PORT=4002
    expose:
      - "4002"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:4002/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 5s
      timeout: 3s
      retries: 3

  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    environment:
      - PORT=4004
      - PAYMENT_FAILURE_RATE=0.08
    expose:
      - "4004"

  booking-service:
    build:
      context: .
      dockerfile: services/booking-service/Dockerfile
    environment:
      - PORT=4003
      - INVENTORY_URL=http://inventory-service:4002
      - PAYMENT_URL=http://payment-service:4004
    expose:
      - "4003"
    depends_on:
      - inventory-service
      - payment-service

  # ---- dos replicas del gateway: mitigan el SPOF discutido en el analisis CAP ----
  gateway-a:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    environment:
      - PORT=4000
      - INSTANCE_ID=A
      - SEARCH_URL=http://search-service:4001
      - INVENTORY_URL=http://inventory-service:4002
      - BOOKING_URL=http://booking-service:4003
      - PAYMENT_URL=http://payment-service:4004
    expose:
      - "4000"
    depends_on:
      - search-service
      - inventory-service
      - booking-service

  gateway-b:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    environment:
      - PORT=4000
      - INSTANCE_ID=B
      - SEARCH_URL=http://search-service:4001
      - INVENTORY_URL=http://inventory-service:4002
      - BOOKING_URL=http://booking-service:4003
      - PAYMENT_URL=http://payment-service:4004
    expose:
      - "4000"
    depends_on:
      - search-service
      - inventory-service
      - booking-service

  load-balancer:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - gateway-a
      - gateway-b
